[package]
name = "ledger_nano_s_poc"
version = "0.1.0"
authors = ["Thomas Eizinger <thomas@eizinger.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.23.0"
ledger-transport-hid = { git = "https://github.com/Zondax/ledger-rs", branch = "master" }
ledger-apdu = { git = "https://github.com/Zondax/ledger-rs", branch = "master" }
anyhow = "1"
pretty_env_logger = "0.4.0"

[dev-dependencies]
tokio = {version = "0.2", features = ["macros"]}
